-- MySQL Script generated by MySQL Workbench
-- Sun Feb 21 20:43:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peritcontrol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peritcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peritcontrol` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `peritcontrol` ;

-- -----------------------------------------------------
-- Table `peritcontrol`.`compania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`compania` (
  `codCompania` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreCom` VARCHAR(150) NOT NULL,
  `estadoCom` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`codCompania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`ramo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`ramo` (
  `codRamo` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcionRam` VARCHAR(150) NOT NULL,
  `codCompania` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`codRamo`),
  INDEX `idk_Ram_Com_idx` (`codCompania` ASC) VISIBLE,
  CONSTRAINT `idk_Ram_Com`
    FOREIGN KEY (`codCompania`)
    REFERENCES `peritcontrol`.`compania` (`codCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`asegurado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`asegurado` (
  `codAsegurado` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreAseg` VARCHAR(150) NOT NULL,
  `direccionRiesgo` VARCHAR(400) NOT NULL,
  `direccionContacto` VARCHAR(400) NULL,
  `contactoAseg` VARCHAR(150) NULL,
  PRIMARY KEY (`codAsegurado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`tiposiniestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`tiposiniestro` (
  `codTipoSin` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripTSiniestro` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`codTipoSin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`siniestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`siniestro` (
  `codSiniestro` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codAsegurado` INT(6) UNSIGNED NOT NULL,
  `codCompania` INT(4) UNSIGNED NOT NULL,
  `codRamo` INT(4) UNSIGNED NOT NULL,
  `codTipoSin` SMALLINT(3) UNSIGNED NOT NULL,
  `numPoliza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codSiniestro`),
  INDEX `idk_codCom_idx` (`codCompania` ASC) VISIBLE,
  INDEX `idk_codAseg_idx` (`codAsegurado` ASC) VISIBLE,
  INDEX `idk_codTipoSin_idx` (`codTipoSin` ASC) VISIBLE,
  INDEX `idk_codRamo_idx` (`codRamo` ASC) VISIBLE,
  INDEX `idk_numpoliza` (`numPoliza` ASC) VISIBLE,
  CONSTRAINT `idk_codCom`
    FOREIGN KEY (`codCompania`)
    REFERENCES `peritcontrol`.`compania` (`codCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_codAseg`
    FOREIGN KEY (`codAsegurado`)
    REFERENCES `peritcontrol`.`asegurado` (`codAsegurado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_codTipoSin`
    FOREIGN KEY (`codTipoSin`)
    REFERENCES `peritcontrol`.`tiposiniestro` (`codTipoSin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_codRamo`
    FOREIGN KEY (`codRamo`)
    REFERENCES `peritcontrol`.`ramo` (`codRamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `peritcontrol`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`telefono` (
  `codTelefono` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `telefonoAseg` INT(9) NOT NULL,
  `codAsegurado` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`codTelefono`),
  INDEX `idk_Aseg_Telf_idx` (`codAsegurado` ASC) VISIBLE,
  CONSTRAINT `idk_Aseg_Telf`
    FOREIGN KEY (`codAsegurado`)
    REFERENCES `peritcontrol`.`asegurado` (`codAsegurado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`usuario` (
  `codUsuario` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreUsr` VARCHAR(100) NOT NULL,
  `passUsr` VARCHAR(100) NOT NULL,
  `estadoUsr` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  `tipoUsr` ENUM('ADMIN', 'COMUN') NOT NULL DEFAULT 'COMUN',
  PRIMARY KEY (`codUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`perito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`perito` (
  `codPerito` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombrePer` VARCHAR(150) NOT NULL,
  `nifPer` VARCHAR(9) NULL,
  `direccionPer` VARCHAR(300) NULL,
  `telefonoPer` INT(9) NULL,
  `emailPer` VARCHAR(255) NULL,
  `estadoPer` ENUM('ACTIVO', 'INACTIVO') NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`codPerito`),
  INDEX `idx_Perito` (`codPerito` ASC) VISIBLE,
  INDEX `idx_nomP` (`nombrePer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`hperito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`hperito` (
  `codHPerito` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `honorarioPer` DECIMAL NULL,
  `locomocionPer` DECIMAL NULL,
  `fotosPer` DECIMAL NULL,
  `ajustesPer` DECIMAL NULL,
  `sumaPer` DECIMAL NULL,
  `ivaPer` DECIMAL NULL,
  `irpfPer` DECIMAL NULL,
  `totalPer` DECIMAL NULL,
  PRIMARY KEY (`codHPerito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`hgabinete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`hgabinete` (
  `codHGabinete` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `honorarioGab` DECIMAL NULL,
  `locomocionGab` DECIMAL NULL,
  `fotosGab` DECIMAL NULL,
  `variosGab` DECIMAL NULL,
  `sumaGab` DECIMAL NULL,
  `ivaGab` DECIMAL NULL,
  `totalGab` DECIMAL NULL,
  PRIMARY KEY (`codHGabinete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`factura` (
  `codFactura` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numFactura` VARCHAR(45) NULL,
  `codHGabinete` INT(8) UNSIGNED NOT NULL,
  `codHPerito` INT(8) UNSIGNED NOT NULL,
  `estadoPagoFac` ENUM('PAGO', 'IMPAGO') NOT NULL DEFAULT 'IMPAGO',
  `mesFacPerito` SMALLINT(2) NULL,
  `anoFacPerito` SMALLINT(2) NULL,
  PRIMARY KEY (`codFactura`),
  INDEX `idk_HGab_idx` (`codHGabinete` ASC) VISIBLE,
  INDEX `idk_HPer_idx` (`codHPerito` ASC) VISIBLE,
  INDEX `idk_numFact` (`numFactura` ASC) VISIBLE,
  CONSTRAINT `idk_HGab`
    FOREIGN KEY (`codHGabinete`)
    REFERENCES `peritcontrol`.`hgabinete` (`codHGabinete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_HPer`
    FOREIGN KEY (`codHPerito`)
    REFERENCES `peritcontrol`.`hperito` (`codHPerito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`registro` (
  `codRegistro` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codPerito` INT(3) UNSIGNED NOT NULL,
  `fechaApertura` DATE NOT NULL,
  `referenciaCia` VARCHAR(45) NOT NULL,
  `codAsegCom` INT(6) UNSIGNED NOT NULL,
  `descripcionReg` VARCHAR(3000) NULL,
  `fechaEntregaPer` DATE NULL,
  `estadoEntrega` ENUM('PENDIENTE', 'ENTREGADO') NOT NULL DEFAULT 'PENDIENTE',
  `estadoReg` BIT NOT NULL DEFAULT 1,
  `codFactura` INT(7) UNSIGNED NOT NULL,
  `fechaCierre` DATE NULL,
  `observaciones` VARCHAR(600) NULL,
  `codUsuario` INT(3) UNSIGNED NOT NULL,
  `numeroReaperturas` SMALLINT(3) NOT NULL DEFAULT 0,
  `tipoRegistro` ENUM('REGISTRO', 'REAPERTURA') NOT NULL DEFAULT 'REGISTRO',
  PRIMARY KEY (`codRegistro`),
  INDEX `idx_Per` (`codPerito` ASC) VISIBLE,
  CONSTRAINT `idk_Per`
    FOREIGN KEY (`codPerito`)
    REFERENCES `peritcontrol`.`perito` (`codPerito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_Usr`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `peritcontrol`.`usuario` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_Fac`
    FOREIGN KEY (`codFactura`)
    REFERENCES `peritcontrol`.`factura` (`codFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_AsCo`
    FOREIGN KEY (`codAsegCom`)
    REFERENCES `peritcontrol`.`siniestro` (`codSiniestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`contadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`contadores` (
  `codContador` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NOT NULL,
  `cuenta` INT(9) NULL,
  `palabra` VARCHAR(45) NULL,
  PRIMARY KEY (`codContador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`tiporeapertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`tiporeapertura` (
  `codTipoReapertura` SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoReapertura` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`codTipoReapertura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peritcontrol`.`reapertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peritcontrol`.`reapertura` (
  `codReapertura` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codRegistroAsociado` INT(6) UNSIGNED NOT NULL,
  `codReaperturaReg` INT(6) UNSIGNED NOT NULL,
  `codTipoReapertura` SMALLINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`codReapertura`),
  INDEX `idk_RegistroAsoc_idx` (`codRegistroAsociado` ASC) VISIBLE,
  INDEX `idk_TipoReapertura_idx` (`codTipoReapertura` ASC) VISIBLE,
  CONSTRAINT `idk_RegistroAsoc`
    FOREIGN KEY (`codRegistroAsociado`)
    REFERENCES `peritcontrol`.`registro` (`codRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idk_TipoReapertura`
    FOREIGN KEY (`codTipoReapertura`)
    REFERENCES `peritcontrol`.`tiporeapertura` (`codTipoReapertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'System' IDENTIFIED BY 'Santo2008__/';

GRANT ALL ON `peritcontrol`.* TO 'System';
GRANT SELECT ON TABLE `peritcontrol`.* TO 'System';
GRANT SELECT, INSERT, TRIGGER ON TABLE `peritcontrol`.* TO 'System';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `peritcontrol`.* TO 'System';
GRANT EXECUTE ON ROUTINE `peritcontrol`.* TO 'System';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
